### ISSUE TITLE
Proposal: Motivation and Purpose

### ISSUE THREAD

**Issue by s-voon** [UBC-MDS/DSCI-532_2024_4_crime-tracker#1]
In a few sentences, provide motivation for why you are creating a dashboard:

Who is your target audience, and what role are you embodying?
What is the problem the target audience is facing and why is it important to solve?
How can your dashboard assist in solving this problem for the intended target audience?

**Comment by WaleedMahmood1** [comment]
I've linked this issue to the branch `proposal-writeup`.
