### ISSUE TITLE
Proposal: Description of the data

### ISSUE THREAD

**Issue by s-voon** [UBC-MDS/DSCI-532_2024_4_crime-tracker#2]
In your proposal, briefly describe the dataset and the variables that you will visualize:

Include how many rows and columns there are in the dataset (that you plan to use).
There should be a clear link to how the dataset and the variables you describe will help you solve your target audience's problem.
Indicate at least one new variable that you are planning to derive/engineer for your visualizations.
If there are no new variables to derive, indicate what additional information you would have liked to have in the dataset to better be able to answer your research questions (even if it is impossible for you to engineer it).
If you are planning to visualize a lot of columns, provide a high level description of the variable types rather than listing every single column.
For example, indicate that the dataset contains a variety of categorical variables for demographics and provide a brief list rather than describing every single variable.
You may also want to consider visualizing a smaller set of variables given the short duration of this project.

**Comment by WaleedMahmood1** [comment]
I've linked this issue to the branch `proposal-writeup`.
