### ISSUE TITLE
Proposal: Research questions

### ISSUE THREAD

**Issue by s-voon** [UBC-MDS/DSCI-532_2024_4_crime-tracker#3]
For this it can be helpful to create a [brief persona description](https://engineering-shiny.org/dont-rush-into-coding.html#building-personas) of a member in your intended target audience
Then, think about what they might want to do with your app and write small user story. User stories are typically written in a narrative style and include:
- The specific context/background of the user
- The overall goal of the user
- Tasks needed to reach that goal
- A hypothetical walkthrough of how the user would accomplish those tasks with your app
- The outcome/action that the user would take based on the information they find in the app

**Comment by WaleedMahmood1** [comment]
I've linked this issue to the branch `proposal-writeup`.
