### ISSUE TITLE
Proposal: App sketch & brief description

### ISSUE THREAD

**Issue by s-voon** [UBC-MDS/DSCI-532_2024_4_crime-tracker#4]
Create a sketch of what you envision your app to look like. Your sketch can be hand-drawn or put together using a graphics editor or slide show software. The sketch should be saved as img/sketch.png and linked in this section of the proposal so that the image shows up when reading the proposal on GitHub.

**Comment by WaleedMahmood1** [comment]
I've linked this issue to the branch `proposal-writeup`.
